class Blanket{
	public static void main(String[] args){
		System.out.println("before re-initalizetion");
		String material ="cooten";
		String color="blue";
		String brand = "silver white";
		String size="mediam";
		int lengthInMeters= 10;
		int widthInMeter=15;
		int price=2000;
		int threadCount=10000;
		double weightInKG=5.4d;
		double thicknessInMM=2.2d;
		float warmthLevel=2.2f;
		float rating=4.3f;
		char grade='B';
		char sizeCode='m';
		boolean washable=true;
		boolean waterproof= false;
		long serialNumber=1234555;
		short warrantyYears=2;
		System.out.println("matiral used in the blanket="+material);
		System.out.println("color of the blanket="+color);
		System.out.println("brand of the blanket="+brand);
		System.out.println("size of the blanket="+size);
		System.out.println("length of the blanket="+lengthInMeters);
		System.out.println("width of the blanket="+widthInMeter);
		System.out.println("price of the blanket="+price);
		System.out.println("thread count="+threadCount);
		System.out.println("weight of the blanket="+weightInKG);
		System.out.println("thickness="+thicknessInMM);
		System.out.println("warmth Level="+warmthLevel);
		System.out.println("rating"+rating);
		System.out.println("grade="+grade);
		System.out.println("size code="+sizeCode);
		System.out.println("washable="+washable);
		System.out.println("waterproof="+waterproof);
		System.out.println("serialNumber");		
		System.out.println("warranty="+warrantyYears);
		material ="lyder";
		color="white";
		brand = "poolar";
		size="large";
	    lengthInMeters= 12;
		widthInMeter=17;
		price=3000;
		threadCount=20000;
		weightInKG=5.7d;
		thicknessInMM=3.2d;
	    warmthLevel=2.2f;
		rating=3.4f;
		grade='A';
		sizeCode='L';
	    washable= true;
		waterproof= false;
		serialNumber=3723423;
		warrantyYears=4;
		System.out.println("matiral used in the blanket="+material);
		System.out.println("color of the blanket="+color);
		System.out.println("brand of the blanket="+brand);
		System.out.println("size of the blanket="+size);
		System.out.println("length of the blanket="+lengthInMeters);
		System.out.println("width of the blanket="+widthInMeter);
		System.out.println("price of the blanket="+price);
		System.out.println("thread count="+threadCount);
		System.out.println("weight of the blanket="+weightInKG);
		System.out.println("thickness="+thicknessInMM);
		System.out.println("warmth Level="+warmthLevel);
		System.out.println("rating"+rating);
		System.out.println("grade="+grade);
		System.out.println("size code="+sizeCode);
		System.out.println("washable="+washable);
		System.out.println("waterproof="+waterproof);
		System.out.println("serialNumber");		
		System.out.println("warranty="+warrantyYears);
		
	}
}
